
default: &default
  adapter: postgis
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ubuntu
  password: d

development:
  <<: *default
  database: itm_development

test:
  <<: *default
  database: itm_test

production:
  <<: *default
  database: itm_production
  username: itsmycargotest
  password: <%= ENV['ITSMYCARGOTEST_DATABASE_PASSWORD'] %>
